# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random

count = 1

def generate_number():
	my_num = (random.sample(range(0,9),4))
	my_num = "".join(map(str,my_num))
	print("\nGuess my 4 digit number:")
	print(my_num)
	return (my_num)

def get_guess():
	guess = input(">>>")
	# if len(guess) != 4:
	# 	print("4 digits please")
	# 	get_guess()
	return guess



def check_bulls(guess, my_num):
	bulls = 0
	guess = str(guess)
	#print(guess)
	for x in range(len(guess)):
		if my_num[x] == guess[x]:
			bulls += 1
	return (bulls)

def check_cows(guess, my_num):
	cows = 0
	guess = str(guess)
	overlap = set([x for x in guess if x in my_num])
	#print (overlap)
	for x in overlap:
		#print("X in cows is:" + x)
		cows = cows +1
	return (cows)

def main(my_number):
	global count
	
	b = get_guess()
	#print("number: " + str(my_number))
	#print("guess:  "+ str(b))

	if my_number != b:
		bulls = check_bulls(b,my_number)
		#print ("Bulls: " + str(bulls))
		cows = check_cows(b,my_number)
		cows = cows - bulls
		#print("Cows: " + str(cows))
		print("{} cows and {} bulls\nGuess again!".format(cows, bulls))
		count = count+1
		main(my_number)

	else:
		print("Nice, you got it!\nGuesses:" + str(count))

main(generate_number())
